apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-service
    app.kubernetes.io/part-of: alpo-studio
  name: build-service
  namespace: alpo-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-service
    spec:
      containers:
      - image: quay.io/jduimovich0/build-service
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
